### ISSUE TITLE
This code let me down

### ISSUE THREAD

**Issue by signaleleven** [RealJTG/Meltdown#2]
and gave me up.
And hurt me.

**Comment by jwiechers** [comment]
This code told a lie.
And made me cry.

But we knew the game and lost it.

**Comment by RomelSan** [comment]
Lol,
BTW... 
Add a link to this article: 
https://www.raspberrypi.org/blog/why-raspberry-pi-isnt-vulnerable-to-spectre-or-meltdown/
It helps to understand how meltdown works.
:)
